spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api?serverTimezone=Asia/Seoul
    username: root
    password:
    hikari:
      maximum-pool-size: 40
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY: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}
      model: claude-3-5-sonnet-latest
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace