package com.example.schedule_manager.domain.schedule.entity;

import com.example.schedule_manager.domain.category.entity.Category;
import com.example.schedule_manager.domain.user.entity.User;
import com.example.schedule_manager.global.common.BaseEntity;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Getter
@Builder
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
@Table(name = "schedules", indexes = @Index(name = "idx_schedule_user_category", columnList = "user_id, category_id"))
public class Schedule extends BaseEntity {

    // IDENTITY는 Hibernate가 생성된 키를 바로 읽어와야 해서 JDBC 배치 INSERT가 안 된다 - 반복 일정을
    // 한 번에 수십 건 저장하는 RecurringScheduleService.materializeOccurrences(ScheduleService.
    // createSchedules)가 이 때문에 saveAll을 호출해도 실제로는 건별 개별 왕복이었다. SEQUENCE 전략으로
    // 바꾸면 Hibernate가 allocationSize만큼 id를 미리 client-side로 받아와 배치 INSERT할 수 있다.
    //
    // 기존 IDENTITY 컬럼이 내부적으로 쓰던 시퀀스(schedules_schedule_id_seq)를 그대로 재사용하지
    // 못했다 - Postgres의 information_schema.sequences는 IDENTITY 컬럼 소유 시퀀스를 스펙상 의도적으로
    // 제외하는데(pg_depend.deptype='i' 필터), ddl-auto: validate가 정확히 그 뷰로 시퀀스 존재를
    // 검증해서 "missing sequence"로 항상 실패한다. 그래서 별도 이름(schedule_id_seq_v2)의 새 시퀀스를
    // 만들고 기존 시퀀스의 마지막 값보다 충분히 위(10,000,000)에서 시작하게 했다 - 컬럼 자체는 여전히
    // "GENERATED BY DEFAULT AS IDENTITY"라 값이 없을 때만 옛 시퀀스를 쓰는데, 이제 Hibernate가 항상
    // 명시적으로 값을 채우므로 그 경로는 사실상 죽어있다(원시 JDBC로 id 없이 insert하는 경우에만 남아있고,
    // 이 프로젝트에선 성능 테스트의 배치 시딩 스크립트가 유일한 예)
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "schedule_id_generator")
    @SequenceGenerator(name = "schedule_id_generator", sequenceName = "schedule_id_seq_v2", allocationSize = 50)
    @Column(name = "schedule_id")
    private Long id;

    private String title;
    private String content;

    @Column(name = "start_at")
    private LocalDateTime startAt;

    @Column(name = "end_at")
    private LocalDateTime endAt;

    @Enumerated(EnumType.STRING)
    private ScheduleStatus status;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    // 반복 일정(RecurringSchedule)에서 미리 생성된 occurrence 인지 표시한다 - 그 반복 규칙이 삭제돼도
    // 이미 지난/진행 중인 일정은 그대로 남겨야 하므로 하드 FK로 묶지 않는다(RecurringSchedule 삭제 시
    // PENDING 상태인 것만 정리하고, 이 컬럼 자체는 그대로 남아 "예전에 어떤 반복에서 나왔는지" 기록으로 쓰인다)
    @Column(name = "recurring_schedule_id")
    private Long recurringScheduleId;

    public void update(String title, String content, LocalDateTime startAt, LocalDateTime endAt,
                        ScheduleStatus status, Category category) {
        this.title = title;
        this.content = content;
        this.startAt = startAt;
        this.endAt = endAt;
        this.status = status;
        this.category = category;
    }
}
